---

- name: Import rpm-gpg keys of additional yum repos
  rpm_key: state=present key={{ item }}
  with_items:
   - RPM-GPG-KEY-rpmfusion-free-fedora-22-primary
   - RPM-GPG-KEY-rpmfusion-nonfree-fedora-22-primary
